user: vitraux
services:
  - http://localhost


#disqus: #paste your Disqus 'shortname'
#map:
#  key: #paste your GoogleMaps API key for geocoding and dynamic maps
#  geocodingService: https://maps.googleapis.com/maps/api/geocode/json

portfolio:
  vitraux:
    visitMap: true
