name: Build
on:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Porphyry
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install Porphyry dependencies
        run:
          npm install
      - name: Build Porphyry
        run:
          npm run build
      - name: Save Porphyry build for later
        uses: actions/upload-artifact@v3
        with:
          name: porphyry-build
          path: build
