name: Acceptance tests
on: 
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and run Argos with proxy and test data
        run: |
          wget https://github.com/Hypertopic/Argos/archive/v4.zip
          unzip v4.zip
          cd Argos-4
          docker-compose up -d
          cd ..
      - uses: nev7n/wait_for_response@v1
        with:
          url: http://localhost
          responseCode: 200
      - name: Create test users
        run: |
          curl --silent -X PUT localhost:5984/_users
          curl --silent -X PUT localhost:5984/_users/org.couchdb.user:alice -H 'Accept:application/json' -H 'Content-Type:application/json' -d '{"name":"alice", "password":"whiterabbit", "roles":[], "type":"user"}'
      - name: Install Porphyry
        run: |
          npm install
          npm run build
      - name: Start Porphyry
        run: npm run preprod &
      - uses: nev7n/wait_for_response@v1
        with:
          url: http://localhost:3000/
          responseCode: 200
      - name: Install test tools
        run: docker pull benel/cucumber-capybara
      - name: Run tests
        run : docker run --rm -v "$(pwd)":/app -t --net="host" --env APP_HOST="http://`hostname`:3000" benel/cucumber-capybara --retry 2 --fail-fast --no-source
        shell: 'script -q -e -c "bash {0}"'
